In [12]:
import pandas as pd

In [14]:
df = pd.read_csv("Dataset.csv")
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [15]:
print('Number of rows and columns:')
print(df.shape)

Number of rows and columns:
(260920, 17)

In [17]:
print('Column names in our dataset:')
print(df.columns.tolist())

Column names in our dataset:
['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder']

In [18]:
print('Data type of each column:')
print(df.dtypes)

Data type of each column:
match_id             int64
inning               int64
batting_team        object
bowling_team        object
over                 int64
ball                 int64
batter              object
bowler              object
non_striker         object
batsman_runs         int64
extra_runs           int64
total_runs           int64
extras_type         object
is_wicket            int64
player_dismissed    object
dismissal_kind      object
fielder             object
dtype: object

In [19]:
print('Description of the dataset:')
df.describe()

Description of the dataset:

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [20]:
missing_values=df.isnull().sum()
print('Number of missing values in each column:')
print(missing_values)

Number of missing values in each column:
match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [21]:
print('Number of unique values in each column:')
for column_name in df.columns:
    unique_count=df[column_name].nunique()
    print(column_name,':',unique_count,'unique values')

Number of unique values in each column:
match_id : 1095 unique values
inning : 6 unique values
batting_team : 19 unique values
bowling_team : 19 unique values
over : 20 unique values
ball : 11 unique values
batter : 673 unique values
bowler : 530 unique values
non_striker : 663 unique values
batsman_runs : 7 unique values
extra_runs : 7 unique values
total_runs : 8 unique values
extras_type : 5 unique values
is_wicket : 2 unique values
player_dismissed : 629 unique values
dismissal_kind : 10 unique values
fielder : 607 unique values

In [22]:
df['extras_type']=df['extras_type'].fillna('none')

In [24]:
print('extras_type column now looks like:')
print(df['extras_type'].value_counts())

extras_type column now looks like:
extras_type
none       246795
wides        8380
legbyes      4001
noballs      1069
byes          673
penalty         2
Name: count, dtype: int64

In [25]:
df['player_dismissed']=df['player_dismissed'].fillna('not_out')
df['dismissal_kind']=df['dismissal_kind'].fillna('not_out')
df['fielder']=df['fielder'].fillna('no_fielder')

In [26]:
print('Dismissal types in the data now:')
print(df['dismissal_kind'].value_counts())

Dismissal types in the data now:
dismissal_kind
not_out                  247970
caught                     8063
bowled                     2212
run out                    1114
lbw                         800
caught and bowled           367
stumped                     358
retired hurt                 15
hit wicket                   15
obstructing the field         3
retired out                   3
Name: count, dtype: int64

In [27]:
print('Rows before remove super overs:',len(df))

Rows before remove super overs: 260920

In [30]:
df=df[df['inning'].isin([1,2])]
df=df.reset_index(drop=True)

In [31]:
print('Rows after removing super overs:',len(df))

Rows after removing super overs: 260759

In [32]:
print('Super over rows removed:',260920-len(df))

Super over rows removed: 161

In [34]:
name_modify={
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru'
}

In [35]:
df['batting_team'] = df['batting_team'].replace(name_modify)
df['bowling_team'] = df['bowling_team'].replace(name_modify)

In [36]:
print('Teams name after modify:')
print(sorted(df['batting_team'].unique()))

Teams name after modify:
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals', 'Gujarat Lions', 'Gujarat Titans', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Rising Pune Supergiants', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']

In [41]:
rows_before_remove_duplicate=len(df)

In [42]:
print('Rows before remove duplicates:',rows_before_remove_duplicate)

Rows before remove duplicates: 260759

In [43]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [46]:
rows_after_remove_duplicate=len(df)

In [48]:
print('Rows after remove duplicates:',rows_after_remove_duplicate)

Rows after remove duplicates: 260759

In [49]:
print('Duplicates removed:',rows_before_remove_duplicate-rows_after_remove_duplicate)

Duplicates removed: 0

In [50]:
print('Cleaned Dataset')
print('Shape:',df.shape)
print()
print('Missing values:')
print(df.isnull().sum())

Cleaned Dataset
Shape: (260759, 17)

Missing values:
match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [51]:
def get_phase(over_number):
    if over_number <= 6:
        return 'Powerplay (1-6)'
    elif over_number <= 15:
        return 'Middle (7-15)'
    else:
        return 'Death (16-20)'

In [54]:
df['over_phase']=df['over'].apply(get_phase)

In [55]:
print('How many balls in each phase:')
print(df['over_phase'].value_counts())

How many balls in each phase:
over_phase
Middle (7-15)      118979
Powerplay (1-6)     95196
Death (16-20)       46584
Name: count, dtype: int64

In [59]:
df['is_boundary']=df['batsman_runs'].apply(lambda x: 1 if x in [4, 6] else 0)

In [60]:
print('Total boundaries hit in IPL history:',df['is_boundary'].sum())

Total boundaries hit in IPL history: 42863

In [61]:
df['is_dot_ball']=((df['batsman_runs']==0)&(df['extras_type']=='none')).astype(int)

In [64]:
print('Total dot balls in IPL history:',df['is_dot_ball'].sum())

Total dot balls in IPL history: 90400

In [65]:
def run_cat(runs):
    if runs==0:
        return 'Dot'
    elif runs==1:
        return 'Single'
    elif runs==2:
        return'Double'
    elif runs==3:
        return'Triple'
    elif runs==4:
        return 'Four'
    else:
        return 'Six'

In [66]:
df['run_category']=df['batsman_runs'].apply(run_cat)

In [67]:
print('Count of each run category:')
print(df['run_category'].value_counts())

Count of each run category:
run_category
Dot       103886
Single     96724
Four       29827
Double     16438
Six        13101
Triple       783
Name: count, dtype: int64

In [68]:
print('Dataframe with new columns:')
print(df.columns.tolist())

Dataframe with new columns:
['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder', 'over_phase', 'is_boundary', 'is_dot_ball', 'run_category']

In [71]:
df[['batting_team','batter','bowler','over','batsman_runs',
'over_phase','is_boundary','is_dot_ball','run_category']].head(8)

,batting_team,batter,bowler,over,batsman_runs,over_phase,is_boundary,is_dot_ball,run_category
0,Kolkata Knight Riders,SC Ganguly,P Kumar,0,0,Powerplay (1-6),0,0,Dot
1,Kolkata Knight Riders,BB McCullum,P Kumar,0,0,Powerplay (1-6),0,1,Dot
2,Kolkata Knight Riders,BB McCullum,P Kumar,0,0,Powerplay (1-6),0,0,Dot
3,Kolkata Knight Riders,BB McCullum,P Kumar,0,0,Powerplay (1-6),0,1,Dot
4,Kolkata Knight Riders,BB McCullum,P Kumar,0,0,Powerplay (1-6),0,1,Dot
5,Kolkata Knight Riders,BB McCullum,P Kumar,0,0,Powerplay (1-6),0,1,Dot
6,Kolkata Knight Riders,BB McCullum,P Kumar,0,0,Powerplay (1-6),0,0,Dot
7,Kolkata Knight Riders,BB McCullum,Z Khan,1,0,Powerplay (1-6),0,1,Dot

In [72]:
#Analysis Data

In [73]:
team_total_runs = df.groupby('batting_team')['total_runs'].sum()
team_total_runs = team_total_runs.sort_values(ascending=False)

In [77]:
print('Total runs scored by each team:')
print(team_total_runs)

Total runs scored by each team:
batting_team
Mumbai Indians                 42133
Royal Challengers Bengaluru    40581
Punjab Kings                   39553
Kolkata Knight Riders          39295
Delhi Capitals                 39164
Chennai Super Kings            38620
Rajasthan Royals               34712
Sunrisers Hyderabad            29034
Deccan Chargers                11463
Gujarat Titans                  7757
Lucknow Super Giants            7510
Pune Warriors                   6358
Gujarat Lions                   4856
Rising Pune Supergiant          2470
Rising Pune Supergiants         2063
Kochi Tuskers Kerala            1901
Name: total_runs, dtype: int64

In [78]:
phase_analysis = df.groupby('over_phase')['total_runs'].mean()

In [79]:
phase_order = ['Powerplay (1-6)','Middle (7-15)','Death (16-20)']
phase_analysis = phase_analysis.loc[phase_order]
phase_analysis = phase_analysis.round(3)

In [81]:
print('Average runs scored per ball in each phase:')
print(phase_analysis)
print()
for phase, avg in phase_analysis.items():
    print(f'  {phase}: {avg} runs per ball on average')

Average runs scored per ball in each phase:
over_phase
Powerplay (1-6)    1.237
Middle (7-15)      1.297
Death (16-20)      1.619
Name: total_runs, dtype: float64

  Powerplay (1-6): 1.237 runs per ball on average
  Middle (7-15): 1.297 runs per ball on average
  Death (16-20): 1.619 runs per ball on average

In [82]:
top_batters = df.groupby('batter')['batsman_runs'].sum()
top_batters = top_batters.sort_values(ascending=False)
top_batters = top_batters.head(10)

In [85]:
print('Top 10 Run Scorers in IPL:')
rank = 1
for player_name,runs in top_batters.items():
    print(f'Rank {rank}:{player_name}—{runs} runs')
    rank=rank+1

Top 10 Run Scorers in IPL:
Rank 1:V Kohli—8004 runs
Rank 2:S Dhawan—6769 runs
Rank 3:RG Sharma—6628 runs
Rank 4:DA Warner—6565 runs
Rank 5:SK Raina—5528 runs
Rank 6:MS Dhoni—5243 runs
Rank 7:AB de Villiers—5162 runs
Rank 8:CH Gayle—4965 runs
Rank 9:RV Uthappa—4952 runs
Rank 10:KD Karthik—4842 runs

In [86]:
boundary_rows = df[df['is_boundary']==1]

In [87]:
team_boundaries = boundary_rows.groupby('batting_team')['is_boundary'].sum()
team_boundaries = team_boundaries.sort_values(ascending=False)

In [88]:
print('Total Boundaries (Fours + Sixes) by Team:')
print(team_boundaries)

Total Boundaries (Fours + Sixes) by Team:
batting_team
Mumbai Indians                 5317
Royal Challengers Bengaluru    5025
Kolkata Knight Riders          4951
Punjab Kings                   4933
Delhi Capitals                 4855
Chennai Super Kings            4704
Rajasthan Royals               4323
Sunrisers Hyderabad            3443
Deccan Chargers                1357
Gujarat Titans                  962
Lucknow Super Giants            909
Pune Warriors                   721
Gujarat Lions                   615
Rising Pune Supergiant          286
Rising Pune Supergiants         239
Kochi Tuskers Kerala            223
Name: is_boundary, dtype: int64

In [91]:
dot_ball=df.groupby('bowling_team').agg(
    Total_Balls=('ball','count'),
    Dot_Balls=('is_dot_ball','sum')
)
dot_ball['Dot_Ball_Percent']=(
    dot_ball['Dot_Balls']/dot_ball['Total_Balls']*100
).round(2)

In [94]:
dot_ball=dot_ball.sort_values('Dot_Ball_Percent',ascending=False)
print('Dot Ball Percentage:')
print(dot_ball)

Dot Ball Percentage:
                             Total_Balls  Dot_Balls  Dot_Ball_Percent
bowling_team
Kochi Tuskers Kerala                1614        626             38.79
Deccan Chargers                     9039       3306             36.57
Rising Pune Supergiant              1928        698             36.20
Pune Warriors                       5457       1929             35.35
Mumbai Indians                     31477      11059             35.13
Chennai Super Kings                28572      10035             35.12
Kolkata Knight Riders              29644      10380             35.02
Gujarat Titans                      5301       1851             34.92
Sunrisers Hyderabad                21698       7553             34.81
Royal Challengers Bengaluru        30140      10378             34.43
Delhi Capitals                     29920      10246             34.24
Rajasthan Royals                   26412       9022             34.16
Lucknow Super Giants                5226       1776             33.98
Punjab Kings                       29176       9907             33.96
Rising Pune Supergiants             1615        539             33.37
Gujarat Lions                       3540       1095             30.93

In [ ]:
#Save datasets

In [95]:
df.to_csv('cleaned_Dataset.csv',index=False)